name: Publish 
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      version:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Version to publish (major,minor,patch,prerelease)'
        # Default value if no value is explicitly provided
        default: 'prerelease'
        # Input has to be provided for the workflow to run
        required: true
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:

        
    # 1. provide Personal Access Token for checkout@v2
    - name: Checkout
      uses: actions/checkout@v2
      with:
          submodules: recursive
          token: ${{ secrets.PUBLISH_PAT }}
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # 2. setup .npmrc it uses NODE_AUTH_TOKEN
    - name: Setup .npmrc file for publish
      run: |
        echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > .npmrc
        echo '@mrbuilder:registry=https://npm.pkg.github.com' >> .npmrc
      env:
        NPM_TOKEN: ${{ secrets.GH_PKG_TOKEN }}
    # 3. configure git user used to push tag
    - name: Configure Git User
      run: |
        git config --global user.email "speajus@gmail.com"
        git config --global user.name "ci@$GITHUB_ACTOR"
        git remote set-url origin https://github.com/mr-builder/mrbuilder.git
   # 4. install ssh key     

    - name: Install dependencies
      run: yarn install

    - name: Publish
      run: |
        lerna publish  --yes ${{ github.event.inputs.version }}